// WBS 4.1, 4.2, 4.6, 4.7 – Template registry (30 popular designs)
import type { TemplateMetadata } from "@/types/template";

export const TEMPLATES: TemplateMetadata[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // PROFESSIONAL & CORPORATE (1–8)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "professional-in",
    name: "Professional",
    description: "Corporate, formal. Best for IT, finance, consulting.",
    version: "1",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#0f172a", accent: "#475569", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-900 border-b border-slate-200 pb-1 mb-2",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: true,
  },

  {
    id: "cascade",
    name: "Cascade",
    description: "Most popular Zety-style. Clear, neat, professional.",
    version: "1",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#1e3a5f", accent: "#2563eb", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-900 border-b-2 border-blue-600 pb-1 mb-3",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: true,
  },

  {
    id: "concept",
    name: "Concept",
    description: "Modern timeline feel. Career progression at a glance.",
    version: "1",
    fontFamily: "sans",
    category: "modern",
    colors: { primary: "#059669", accent: "#10b981", text: "#1f2937", muted: "#6b7280", border: "#d1d5db" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-bold text-slate-900 border-l-4 border-emerald-600 pl-3 mb-3",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "tags",
    experienceVariant: "timeline",
    sectionTitleVariant: "left-border",
    trialAvailable: true,
  },

  {
    id: "crisp",
    name: "Crisp",
    description: "Creative yet readable. Design & marketing roles.",
    version: "1",
    fontFamily: "sans",
    category: "creative",
    colors: { primary: "#7c3aed", accent: "#8b5cf6", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "normal", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-800 pb-1 mb-2 text-xs tracking-widest uppercase",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    trialAvailable: false,
  },

  {
    id: "cubic",
    name: "Cubic",
    description: "Versatile. Excellent readability for dense resumes.",
    version: "1",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#374151", accent: "#4b5563", text: "#1f2937", muted: "#9ca3af", border: "#e5e7eb" },
    layout: { spacing: "compact", lineHeight: "tight", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-800 border-b border-slate-300 pb-0.5 mb-2 text-sm",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: false,
  },

  {
    id: "diamond",
    name: "Diamond",
    description: "Serif classic. Ideal for extensive work history.",
    version: "1",
    fontFamily: "serif",
    category: "classic",
    colors: { primary: "#1e293b", accent: "#475569", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-serif",
    sectionTitleClass: "font-semibold text-slate-900 border-b-2 border-slate-300 pb-2 mb-4",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "bold",
    trialAvailable: false,
  },

  {
    id: "enfold",
    name: "Enfold",
    description: "Two-column. Skills & summary in tinted sidebar.",
    version: "1",
    fontFamily: "sans",
    category: "modern",
    colors: { primary: "#0369a1", accent: "#0ea5e9", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: {
      spacing: "normal",
      lineHeight: "normal",
      columns: "two-column",
      layoutType: "two-column",
      sidebarSections: ["contact", "skills", "languages", "certifications"],
    },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-900 mb-2 text-sm uppercase tracking-wide",
    accentClass: "",
    layoutVariant: "two-column",
    headerVariant: "top-bar",
    skillsVariant: "bars",
    experienceVariant: "default",
    sectionTitleVariant: "filled-bg",
    sidebarBg: true,
    trialAvailable: true,
  },

  {
    id: "influx",
    name: "Influx",
    description: "Elegant serif feel. Traditional industries.",
    version: "1",
    fontFamily: "serif",
    category: "classic",
    colors: { primary: "#4c1d95", accent: "#6d28d9", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "normal", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-serif",
    sectionTitleClass: "font-semibold text-slate-800 border-b border-slate-300 pb-1 mb-2 text-xs tracking-wider uppercase",
    accentClass: "border-l-2 border-violet-400 pl-3",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "dots",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    trialAvailable: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MINIMAL & ATS-FRIENDLY (9–16)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "minimal-in",
    name: "Minimal",
    description: "Sparse, elegant. Tech and engineering.",
    version: "1",
    fontFamily: "sans",
    category: "minimal",
    colors: { primary: "#4b5563", accent: "#6b7280", text: "#374151", muted: "#9ca3af", border: "#f3f4f6" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-medium text-slate-600 border-b border-slate-100 pb-2 mb-4 text-xs tracking-widest uppercase",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "plain",
    trialAvailable: true,
  },

  {
    id: "minimo",
    name: "Minimo",
    description: "Minimalist with modern twist. Clean lines.",
    version: "1",
    fontFamily: "sans",
    category: "minimal",
    colors: { primary: "#0d9488", accent: "#14b8a6", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-medium text-teal-800 pb-1 mb-3 text-sm",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "tags",
    experienceVariant: "timeline",
    sectionTitleVariant: "underline",
    trialAvailable: false,
  },

  {
    id: "ats-minimal",
    name: "ATS Minimal",
    description: "Ultra-simple. Max ATS compatibility, no graphics.",
    version: "1",
    fontFamily: "sans",
    category: "ats",
    colors: { primary: "#171717", accent: "#404040", text: "#262626", muted: "#737373", border: "#a3a3a3" },
    layout: { spacing: "compact", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-neutral-900 mb-1 text-sm",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "compact",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: true,
  },

  {
    id: "ats-strict",
    name: "ATS Strict",
    description: "Zero formatting risk. Designed for ATS systems.",
    version: "1",
    fontFamily: "sans",
    category: "ats",
    colors: { primary: "#1e3a8a", accent: "#3b82f6", text: "#1e293b", muted: "#64748b", border: "#cbd5e1" },
    layout: { spacing: "compact", lineHeight: "tight", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-bold text-slate-900 border-b border-slate-400 pb-0.5 mb-2",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: false,
  },

  {
    id: "nanica",
    name: "Nanica",
    description: "Traditional format. Straightforward and clear.",
    version: "1",
    fontFamily: "serif",
    category: "classic",
    colors: { primary: "#78350f", accent: "#92400e", text: "#44403c", muted: "#78716c", border: "#d6d3d1" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-serif",
    sectionTitleClass: "font-semibold text-amber-950 border-b border-amber-700 pb-1 mb-2",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: false,
  },

  {
    id: "modern",
    name: "Modern",
    description: "Contemporary layout. Timeline career story.",
    version: "1",
    fontFamily: "sans",
    category: "modern",
    colors: { primary: "#0c4a6e", accent: "#0284c7", text: "#1e293b", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-bold text-slate-900 border-l-4 border-sky-700 pl-3 mb-2",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "tags",
    experienceVariant: "timeline",
    sectionTitleVariant: "left-border",
    trialAvailable: true,
  },

  {
    id: "skill-based",
    name: "Skill-Based",
    description: "Skills-first layout. Career changers & graduates.",
    version: "1",
    fontFamily: "sans",
    category: "fresher",
    colors: { primary: "#166534", accent: "#22c55e", text: "#1f2937", muted: "#6b7280", border: "#d1d5db" },
    layout: { spacing: "normal", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-900 border-b-2 border-green-600 pb-1 mb-3",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "filled-bg",
    trialAvailable: false,
  },

  {
    id: "hybrid",
    name: "Hybrid",
    description: "Combines functional and reverse-chronological.",
    version: "1",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#5b21b6", accent: "#7c3aed", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-800 border-b border-violet-300 pb-1 mb-2 text-xs tracking-wider",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "tags",
    experienceVariant: "timeline",
    sectionTitleVariant: "uppercase",
    trialAvailable: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FRESHER & STUDENT (17–20)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "fresher-in",
    name: "Fresher",
    description: "Clean, spacious. Campus placements & first jobs.",
    version: "1",
    fontFamily: "sans",
    category: "fresher",
    colors: { primary: "#1e40af", accent: "#3b82f6", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-medium text-blue-900 border-b border-blue-200 pb-2 mb-3 text-sm",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: true,
  },

  {
    id: "student",
    name: "Student",
    description: "College and internship applications.",
    version: "1",
    fontFamily: "sans",
    category: "fresher",
    colors: { primary: "#ea580c", accent: "#f97316", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-medium text-orange-900 border-b border-orange-200 pb-2 mb-3 text-sm",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "filled-bg",
    trialAvailable: false,
  },

  {
    id: "muse",
    name: "Muse",
    description: "Dark sidebar impact. Creative graduates & designers.",
    version: "1",
    fontFamily: "serif",
    category: "creative",
    colors: { primary: "#9d174d", accent: "#db2777", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: {
      spacing: "normal",
      lineHeight: "relaxed",
      columns: "two-column",
      layoutType: "dark-sidebar",
      sidebarSections: ["contact", "skills", "languages", "awards"],
    },
    wrapperClass: "font-serif",
    sectionTitleClass: "font-semibold text-pink-900 pb-1 mb-2 text-xs tracking-wider",
    accentClass: "",
    layoutVariant: "dark-sidebar",
    headerVariant: "dark-sidebar",
    skillsVariant: "dots",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    trialAvailable: false,
  },

  {
    id: "combined",
    name: "Combined",
    description: "Mix of formats. Flexible for various levels.",
    version: "1",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#0f766e", accent: "#0d9488", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-900 border-l-4 border-teal-600 pl-3 mb-2",
    accentClass: "border-l-2 border-teal-200 pl-4",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "left-border",
    trialAvailable: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EXECUTIVE & MID-CAREER (21–26)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "midcareer-in",
    name: "Mid-Career",
    description: "Bold timeline headings. For 5+ years experience.",
    version: "1",
    fontFamily: "sans",
    category: "corporate",
    colors: { primary: "#059669", accent: "#10b981", text: "#1f2937", muted: "#4b5563", border: "#d1d5db" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-bold text-slate-900 border-b-2 border-emerald-600 pb-1 mb-3 text-sm",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "bars",
    experienceVariant: "timeline",
    sectionTitleVariant: "filled-bg",
    trialAvailable: true,
  },

  {
    id: "executive",
    name: "Executive",
    description: "Serif prestige. CEO, C-suite, senior leadership.",
    version: "1",
    fontFamily: "serif",
    category: "executive",
    colors: { primary: "#1e293b", accent: "#475569", text: "#334155", muted: "#64748b", border: "#cbd5e1" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-serif",
    sectionTitleClass: "font-bold text-slate-900 mb-3 text-base",
    accentClass: "border-l-4 border-slate-700 pl-4",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "bold",
    trialAvailable: false,
  },

  {
    id: "executive-modern",
    name: "Executive Modern",
    description: "Two-column sophisticated. Skill bars in sidebar.",
    version: "1",
    fontFamily: "sans",
    category: "executive",
    colors: { primary: "#0c4a6e", accent: "#0369a1", text: "#1e293b", muted: "#64748b", border: "#e2e8f0" },
    layout: {
      spacing: "spacious",
      lineHeight: "relaxed",
      columns: "two-column",
      layoutType: "two-column",
      sidebarSections: ["contact", "skills", "certifications", "languages"],
    },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-bold text-slate-900 uppercase tracking-wider mb-3 text-sm",
    accentClass: "",
    layoutVariant: "two-column",
    headerVariant: "top-bar",
    skillsVariant: "bars",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    sidebarBg: true,
    trialAvailable: false,
  },

  {
    id: "tech",
    name: "Tech",
    description: "Monospace. IT & engineering expertise.",
    version: "1",
    fontFamily: "mono",
    category: "tech",
    colors: { primary: "#14532d", accent: "#15803d", text: "#1f2937", muted: "#6b7280", border: "#d1d5db" },
    layout: { spacing: "compact", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-mono",
    sectionTitleClass: "font-bold text-slate-900 border-l-4 border-green-700 pl-2 mb-2 text-sm",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "tags",
    experienceVariant: "timeline",
    sectionTitleVariant: "left-border",
    trialAvailable: true,
  },

  {
    id: "it",
    name: "IT Professional",
    description: "IT job applications with skill progress bars.",
    version: "1",
    fontFamily: "sans",
    category: "tech",
    colors: { primary: "#1e40af", accent: "#2563eb", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "compact", lineHeight: "tight", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-900 border-b-2 border-blue-600 pb-0.5 mb-2 text-sm",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "bars",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: false,
  },

  {
    id: "iconic",
    name: "Iconic",
    description: "Dark sidebar with pink accent. Designer & creative.",
    version: "1",
    fontFamily: "sans",
    category: "creative",
    colors: { primary: "#be185d", accent: "#ec4899", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: {
      spacing: "normal",
      lineHeight: "relaxed",
      columns: "two-column",
      layoutType: "dark-sidebar",
      sidebarSections: ["contact", "skills", "languages", "certifications"],
    },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-bold pb-1 mb-2 text-xs tracking-widest",
    accentClass: "",
    layoutVariant: "dark-sidebar",
    headerVariant: "dark-sidebar",
    skillsVariant: "dots",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    trialAvailable: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CREATIVE & UNIQUE (27–30)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "creative-in",
    name: "Creative",
    description: "Dark sidebar layout. Design, marketing, content.",
    version: "1",
    fontFamily: "serif",
    category: "creative",
    colors: { primary: "#7c3aed", accent: "#8b5cf6", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: {
      spacing: "normal",
      lineHeight: "relaxed",
      columns: "two-column",
      layoutType: "dark-sidebar",
      sidebarSections: ["contact", "skills", "certifications", "languages"],
    },
    wrapperClass: "font-serif",
    sectionTitleClass: "font-semibold pb-1 mb-2 text-sm tracking-wide",
    accentClass: "",
    layoutVariant: "dark-sidebar",
    headerVariant: "dark-sidebar",
    skillsVariant: "dots",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    trialAvailable: true,
  },

  {
    id: "initials",
    name: "Initials",
    description: "Dark sidebar serif. Highlights personal brand.",
    version: "1",
    fontFamily: "serif",
    category: "creative",
    colors: { primary: "#6b21a8", accent: "#9333ea", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: {
      spacing: "spacious",
      lineHeight: "relaxed",
      columns: "two-column",
      layoutType: "dark-sidebar",
      sidebarSections: ["contact", "skills", "languages", "awards"],
    },
    wrapperClass: "font-serif",
    sectionTitleClass: "font-bold mb-2 text-base",
    accentClass: "",
    layoutVariant: "dark-sidebar",
    headerVariant: "dark-sidebar",
    skillsVariant: "dots",
    experienceVariant: "timeline",
    sectionTitleVariant: "bold",
    trialAvailable: false,
  },

  {
    id: "traditional",
    name: "Traditional",
    description: "Classic straightforward format.",
    version: "1",
    fontFamily: "serif",
    category: "classic",
    colors: { primary: "#292524", accent: "#57534e", text: "#44403c", muted: "#78716c", border: "#d6d3d1" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-serif",
    sectionTitleClass: "font-semibold text-stone-900 border-b-2 border-stone-500 pb-1 mb-2",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: false,
  },

  {
    id: "general",
    name: "General",
    description: "Versatile for most industries.",
    version: "1",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#155e75", accent: "#0e7490", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    sectionTitleClass: "font-semibold text-slate-900 border-b border-cyan-700 pb-1 mb-2",
    accentClass: "",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    trialAvailable: false,
  },

];

// ─── Aliases & helpers ────────────────────────────────────────────────────────

export const TEMPLATE_ALIASES: Record<string, string> = {
  "professional-v1": "professional-in",
  "trial-classic": "midcareer-in",
  "trial-modern": "professional-in",
  "trial-bold": "midcareer-in",
  "trial-minimal": "minimal-in",
  "trial-professional": "professional-in",
};

export function resolveTemplateId(id: string): string {
  return TEMPLATE_ALIASES[id] ?? id;
}

export function getTemplate(id: string): TemplateMetadata | null {
  const resolved = resolveTemplateId(id);
  return TEMPLATES.find((t) => t.id === resolved) ?? null;
}

export function getTemplateOrFallback(id: string): TemplateMetadata {
  return getTemplate(id) ?? TEMPLATES[0];
}

export const AVAILABLE_TEMPLATE_IDS = TEMPLATES.map((t) => t.id);
export const TRIAL_TEMPLATE_IDS = TEMPLATES.filter((t) => t.trialAvailable).map((t) => t.id);
