// WBS 4.1, 4.2, 4.6, 4.7 – Template registry (30 designs, each with unique 7-axis variant combo)
//
// Axis matrix per template:
//   layoutVariant  : single | two-column | dark-sidebar
//   headerVariant  : default | top-bar | centered | split | dark-sidebar
//   skillsVariant  : plain | compact | tags | dots | bars | categories | icon-grid
//   experienceVariant : default | timeline | compact
//   sectionTitleVariant: underline | left-border | uppercase | filled-bg | bold | plain | double-rule | tab | dot-prefix
//   accentStrip    : boolean  (full-height left edge 4px color bar)
//   showInitialsAvatar: boolean (initials circle in header)

import type { TemplateMetadata } from "@/types/template";

export const TEMPLATES: TemplateMetadata[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // PROFESSIONAL & CORPORATE (1–8)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "professional-in",
    name: "Professional",
    description: "Corporate standard. Clean underline titles, bullet experience.",
    version: "2",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#0f172a", accent: "#475569", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: true,
  },

  {
    id: "cascade",
    name: "Cascade",
    description: "Full-width color bar header, tag-pill skills, sharp accent.",
    version: "2",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#1e3a5f", accent: "#2563eb", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: true,
  },

  {
    id: "concept",
    name: "Concept",
    description: "Timeline career story, left-border headings, tag skills.",
    version: "2",
    fontFamily: "sans",
    category: "modern",
    colors: { primary: "#059669", accent: "#10b981", text: "#1f2937", muted: "#6b7280", border: "#d1d5db" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "tags",
    experienceVariant: "timeline",
    sectionTitleVariant: "left-border",
    accentStrip: false,
    showInitialsAvatar: false,
    sectionIcons: true,
    trialAvailable: true,
  },

  {
    id: "crisp",
    name: "Crisp",
    description: "Centered header with initials avatar, uppercase headings.",
    version: "2",
    fontFamily: "sans",
    category: "creative",
    colors: { primary: "#7c3aed", accent: "#8b5cf6", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "normal", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    accentStrip: false,
    showInitialsAvatar: true,
    showPhotoPlaceholder: false,
    sectionIcons: false,
    trialAvailable: false,
  },

  {
    id: "cubic",
    name: "Cubic",
    description: "Split two-zone header, compact one-line experience, icon-grid skills.",
    version: "2",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#374151", accent: "#4b5563", text: "#1f2937", muted: "#9ca3af", border: "#e5e7eb" },
    layout: { spacing: "compact", lineHeight: "tight", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "split",
    skillsVariant: "icon-grid",
    experienceVariant: "compact",
    sectionTitleVariant: "underline",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  {
    id: "diamond",
    name: "Diamond",
    description: "Split header serif classic, double-rule headings, plain skills.",
    version: "2",
    fontFamily: "serif",
    category: "classic",
    colors: { primary: "#1e293b", accent: "#475569", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-serif",
    layoutVariant: "single",
    headerVariant: "split",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "double-rule",
    accentStrip: false,
    showInitialsAvatar: false,
    showPhotoPlaceholder: true,
    trialAvailable: false,
  },

  {
    id: "enfold",
    name: "Enfold",
    description: "Two-column tinted sidebar, filled-bg headings, skill bars.",
    version: "2",
    fontFamily: "sans",
    category: "modern",
    colors: { primary: "#0369a1", accent: "#0ea5e9", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: {
      spacing: "normal", lineHeight: "normal", columns: "two-column", layoutType: "two-column",
      sidebarSections: ["contact", "skills", "languages", "certifications"],
    },
    wrapperClass: "font-sans",
    layoutVariant: "two-column",
    headerVariant: "top-bar",
    skillsVariant: "bars",
    experienceVariant: "default",
    sectionTitleVariant: "filled-bg",
    sidebarBg: true,
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: true,
  },

  {
    id: "influx",
    name: "Influx",
    description: "Serif accent strip, tab-badge headings, categorised skills.",
    version: "2",
    fontFamily: "serif",
    category: "classic",
    colors: { primary: "#4c1d95", accent: "#6d28d9", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "normal", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-serif",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "categories",
    experienceVariant: "default",
    sectionTitleVariant: "tab",
    accentStrip: true,
    showInitialsAvatar: false,
    sectionIcons: true,
    trialAvailable: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MINIMAL & ATS (9–16)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "minimal-in",
    name: "Minimal",
    description: "Stripped-back, plain muted headings, no decoration.",
    version: "2",
    fontFamily: "sans",
    category: "minimal",
    colors: { primary: "#4b5563", accent: "#6b7280", text: "#374151", muted: "#9ca3af", border: "#f3f4f6" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "plain",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: true,
  },

  {
    id: "minimo",
    name: "Minimo",
    description: "Top-bar header, timeline entries, icon-grid skills, dot-prefix headings.",
    version: "2",
    fontFamily: "sans",
    category: "minimal",
    colors: { primary: "#0d9488", accent: "#14b8a6", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "icon-grid",
    experienceVariant: "timeline",
    sectionTitleVariant: "dot-prefix",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  {
    id: "ats-minimal",
    name: "ATS Minimal",
    description: "Zero graphics, compact comma-skills, default header, underline headings.",
    version: "2",
    fontFamily: "sans",
    category: "ats",
    colors: { primary: "#171717", accent: "#404040", text: "#262626", muted: "#737373", border: "#a3a3a3" },
    layout: { spacing: "compact", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "compact",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: true,
  },

  {
    id: "ats-strict",
    name: "ATS Strict",
    description: "Single-line compact experience, no bullets, maximum ATS safety.",
    version: "2",
    fontFamily: "sans",
    category: "ats",
    colors: { primary: "#1e3a8a", accent: "#3b82f6", text: "#1e293b", muted: "#64748b", border: "#cbd5e1" },
    layout: { spacing: "compact", lineHeight: "tight", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "compact",
    sectionTitleVariant: "underline",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  {
    id: "nanica",
    name: "Nanica",
    description: "Serif, split two-zone header, double-rule headings, classic feel.",
    version: "2",
    fontFamily: "serif",
    category: "classic",
    colors: { primary: "#78350f", accent: "#92400e", text: "#44403c", muted: "#78716c", border: "#d6d3d1" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-serif",
    layoutVariant: "single",
    headerVariant: "split",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "double-rule",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  {
    id: "modern",
    name: "Modern",
    description: "Accent strip, top-bar header, timeline entries, left-border headings.",
    version: "2",
    fontFamily: "sans",
    category: "modern",
    colors: { primary: "#0c4a6e", accent: "#0284c7", text: "#1e293b", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "tags",
    experienceVariant: "timeline",
    sectionTitleVariant: "left-border",
    accentStrip: true,
    showInitialsAvatar: false,
    sectionIcons: true,
    trialAvailable: true,
  },

  {
    id: "skill-based",
    name: "Skill-Based",
    description: "Skills-first centered header, filled-bg headings, category groups.",
    version: "2",
    fontFamily: "sans",
    category: "fresher",
    colors: { primary: "#166534", accent: "#22c55e", text: "#1f2937", muted: "#6b7280", border: "#d1d5db" },
    layout: { spacing: "normal", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "categories",
    experienceVariant: "default",
    sectionTitleVariant: "filled-bg",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  {
    id: "hybrid",
    name: "Hybrid",
    description: "Top-bar header, timeline + tags, tab-badge section headings.",
    version: "2",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#5b21b6", accent: "#7c3aed", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "tags",
    experienceVariant: "timeline",
    sectionTitleVariant: "tab",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FRESHER & STUDENT (17–20)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "fresher-in",
    name: "Fresher",
    description: "Centered header with avatar initials, tag skills, spacious layout.",
    version: "2",
    fontFamily: "sans",
    category: "fresher",
    colors: { primary: "#1e40af", accent: "#3b82f6", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "underline",
    accentStrip: false,
    showInitialsAvatar: true,
    trialAvailable: true,
  },

  {
    id: "student",
    name: "Student",
    description: "Centered + avatar, icon-grid skills, tab headings. Campus-ready.",
    version: "2",
    fontFamily: "sans",
    category: "fresher",
    colors: { primary: "#ea580c", accent: "#f97316", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "centered",
    skillsVariant: "icon-grid",
    experienceVariant: "default",
    sectionTitleVariant: "tab",
    accentStrip: false,
    showInitialsAvatar: true,
    showPhotoPlaceholder: false,
    sectionIcons: false,
    trialAvailable: false,
  },

  {
    id: "muse",
    name: "Muse",
    description: "Dark pink sidebar, dot-scale skills, uppercase headings on right.",
    version: "2",
    fontFamily: "serif",
    category: "creative",
    colors: { primary: "#9d174d", accent: "#db2777", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: {
      spacing: "normal", lineHeight: "relaxed", columns: "two-column", layoutType: "dark-sidebar",
      sidebarSections: ["contact", "skills", "languages", "awards"],
    },
    wrapperClass: "font-serif",
    layoutVariant: "dark-sidebar",
    headerVariant: "dark-sidebar",
    skillsVariant: "dots",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  {
    id: "combined",
    name: "Combined",
    description: "Accent strip, left-border headings, categorised skills, default header.",
    version: "2",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#0f766e", accent: "#0d9488", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "categories",
    experienceVariant: "default",
    sectionTitleVariant: "left-border",
    accentStrip: true,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EXECUTIVE & MID-CAREER (21–26)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "midcareer-in",
    name: "Mid-Career",
    description: "Top-bar header, timeline + bars, filled-bg headings. 5+ years.",
    version: "2",
    fontFamily: "sans",
    category: "corporate",
    colors: { primary: "#059669", accent: "#10b981", text: "#1f2937", muted: "#4b5563", border: "#d1d5db" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "bars",
    experienceVariant: "timeline",
    sectionTitleVariant: "filled-bg",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: true,
  },

  {
    id: "executive",
    name: "Executive",
    description: "Split header, accent strip serif, bold headings, plain skills. C-suite.",
    version: "2",
    fontFamily: "serif",
    category: "executive",
    colors: { primary: "#1e293b", accent: "#475569", text: "#334155", muted: "#64748b", border: "#cbd5e1" },
    layout: { spacing: "spacious", lineHeight: "relaxed", columns: "single" },
    wrapperClass: "font-serif",
    layoutVariant: "single",
    headerVariant: "split",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "bold",
    accentStrip: true,
    showInitialsAvatar: false,
    showPhotoPlaceholder: true,
    sectionIcons: false,
    trialAvailable: false,
  },

  {
    id: "executive-modern",
    name: "Executive Modern",
    description: "Two-column, top-bar, skill bars + categories, uppercase headings.",
    version: "2",
    fontFamily: "sans",
    category: "executive",
    colors: { primary: "#0c4a6e", accent: "#0369a1", text: "#1e293b", muted: "#64748b", border: "#e2e8f0" },
    layout: {
      spacing: "spacious", lineHeight: "relaxed", columns: "two-column", layoutType: "two-column",
      sidebarSections: ["contact", "skills", "certifications", "languages"],
    },
    wrapperClass: "font-sans",
    layoutVariant: "two-column",
    headerVariant: "top-bar",
    skillsVariant: "bars",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    sidebarBg: true,
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  {
    id: "tech",
    name: "Tech",
    description: "Monospace, left-border headings, tag skills, timeline entries.",
    version: "2",
    fontFamily: "mono",
    category: "tech",
    colors: { primary: "#14532d", accent: "#15803d", text: "#1f2937", muted: "#6b7280", border: "#d1d5db" },
    layout: { spacing: "compact", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-mono",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "tags",
    experienceVariant: "timeline",
    sectionTitleVariant: "left-border",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: true,
  },

  {
    id: "it",
    name: "IT Professional",
    description: "Top-bar header, compact experience, dot-prefix headings, skill bars.",
    version: "2",
    fontFamily: "sans",
    category: "tech",
    colors: { primary: "#1e40af", accent: "#2563eb", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "compact", lineHeight: "tight", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "bars",
    experienceVariant: "compact",
    sectionTitleVariant: "dot-prefix",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  {
    id: "iconic",
    name: "Iconic",
    description: "Dark sidebar dot skills, uppercase headings. Designer-forward.",
    version: "2",
    fontFamily: "sans",
    category: "creative",
    colors: { primary: "#be185d", accent: "#ec4899", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: {
      spacing: "normal", lineHeight: "relaxed", columns: "two-column", layoutType: "dark-sidebar",
      sidebarSections: ["contact", "skills", "languages", "certifications"],
    },
    wrapperClass: "font-sans",
    layoutVariant: "dark-sidebar",
    headerVariant: "dark-sidebar",
    skillsVariant: "dots",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CREATIVE & UNIQUE (27–30)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "creative-in",
    name: "Creative",
    description: "Dark purple sidebar, dot skills, uppercase headings. Portfolio style.",
    version: "2",
    fontFamily: "serif",
    category: "creative",
    colors: { primary: "#7c3aed", accent: "#8b5cf6", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: {
      spacing: "normal", lineHeight: "relaxed", columns: "two-column", layoutType: "dark-sidebar",
      sidebarSections: ["contact", "skills", "certifications", "languages"],
    },
    wrapperClass: "font-serif",
    layoutVariant: "dark-sidebar",
    headerVariant: "dark-sidebar",
    skillsVariant: "dots",
    experienceVariant: "default",
    sectionTitleVariant: "uppercase",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: true,
  },

  {
    id: "initials",
    name: "Initials",
    description: "Dark sidebar with avatar initials, serif, bold headings, timeline.",
    version: "2",
    fontFamily: "serif",
    category: "creative",
    colors: { primary: "#6b21a8", accent: "#9333ea", text: "#374151", muted: "#6b7280", border: "#e5e7eb" },
    layout: {
      spacing: "spacious", lineHeight: "relaxed", columns: "two-column", layoutType: "dark-sidebar",
      sidebarSections: ["contact", "skills", "languages", "awards"],
    },
    wrapperClass: "font-serif",
    layoutVariant: "dark-sidebar",
    headerVariant: "dark-sidebar",
    skillsVariant: "dots",
    experienceVariant: "timeline",
    sectionTitleVariant: "bold",
    accentStrip: false,
    showInitialsAvatar: true,
    showPhotoPlaceholder: false,
    sectionIcons: true,
    trialAvailable: false,
  },

  {
    id: "traditional",
    name: "Traditional",
    description: "Serif, accent strip, double-rule headings, plain skills.",
    version: "2",
    fontFamily: "serif",
    category: "classic",
    colors: { primary: "#292524", accent: "#57534e", text: "#44403c", muted: "#78716c", border: "#d6d3d1" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-serif",
    layoutVariant: "single",
    headerVariant: "default",
    skillsVariant: "plain",
    experienceVariant: "default",
    sectionTitleVariant: "double-rule",
    accentStrip: true,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

  {
    id: "general",
    name: "General",
    description: "Top-bar header, tag skills, dot-prefix headings, versatile.",
    version: "2",
    fontFamily: "sans",
    category: "professional",
    colors: { primary: "#155e75", accent: "#0e7490", text: "#334155", muted: "#64748b", border: "#e2e8f0" },
    layout: { spacing: "normal", lineHeight: "normal", columns: "single" },
    wrapperClass: "font-sans",
    layoutVariant: "single",
    headerVariant: "top-bar",
    skillsVariant: "tags",
    experienceVariant: "default",
    sectionTitleVariant: "dot-prefix",
    accentStrip: false,
    showInitialsAvatar: false,
    trialAvailable: false,
  },

];

// ─── Aliases & helpers ────────────────────────────────────────────────────────

export const TEMPLATE_ALIASES: Record<string, string> = {
  "professional-v1": "professional-in",
  "trial-classic": "midcareer-in",
  "trial-modern": "professional-in",
  "trial-bold": "midcareer-in",
  "trial-minimal": "minimal-in",
  "trial-professional": "professional-in",
};

export function resolveTemplateId(id: string): string {
  return TEMPLATE_ALIASES[id] ?? id;
}

export function getTemplate(id: string): import("@/types/template").TemplateMetadata | null {
  const resolved = resolveTemplateId(id);
  return TEMPLATES.find((t) => t.id === resolved) ?? null;
}

export function getTemplateOrFallback(id: string): import("@/types/template").TemplateMetadata {
  return getTemplate(id) ?? TEMPLATES[0];
}

export const AVAILABLE_TEMPLATE_IDS = TEMPLATES.map((t) => t.id);
export const TRIAL_TEMPLATE_IDS = TEMPLATES.filter((t) => t.trialAvailable).map((t) => t.id);
